name: Gate

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: use volta to setup node and yarn
        uses: volta-cli/action@v4

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build bundles
        run: yarn build