name: Gate

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Volta
        run: |
          curl https://get.volta.sh | bash
          export PATH="$HOME/.volta/bin:$PATH"

      - name: Use Node.js and Yarn from Volta
        run: |
          volta install node
          volta install yarn
          node -v
          yarn -v

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build the project
        run: yarn build