name: Release Execution Node

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release'
        required: true
        default: '1.0.0'

jobs:
  build-arm-binary:
    name: Build ARM Binary for Execution Node
    runs-on: ubuntu-22.04-arm

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: use volta to setup node and yarn
        uses: volta-cli/action@v4

      - name: install dependencies
        run: yarn install

      - name: build for ARM
        run: yarn package:execution-node:for-pi

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: execution-node-binary
      #     path: ./execution-node