name: Release Execution Node

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release"
        required: true
        default: "1.0.0"

jobs:
  build-arm-binary:
    name: Build ARM Binary for Execution Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU and Buildx
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create output directory
        run: mkdir -p ./output

      - name: Build ARM Binary with Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --build-arg VERSION=${{ github.event.inputs.version }} \
            -o type=local,dest=./output \
            -t execution-node-builder:latest \
            -f ./.github/workflows/execution-node-builder.Dockerfile .

      - name: Upload ARM Binary
        uses: actions/upload-artifact@v3
        with:
          name: execution-node-binary
          path: ./output/execution-node